### ISSUE TITLE
Ripple Wallet App Not Working with Windows 10

### ISSUE THREAD

**Issue by sdweber** [LedgerHQ/ledger-wallet-ripple#14]
Greetings,

I found out I'm not alone with this issue, as several online discussions address problems running the native program (ledger wallet for ripple) on Windows (I'm running Windows 10).  Basically, the app doesn't work.

I've tried several software installs, including both the "setup_ledger_wallet_ripple_win_x64" and "setup_ledger_wallet_ripple_win_x86" versions.  For the x64 version, which downloads via the applicable Ledger webpage link, the app doesn't come up at all.  For the x86 version, the app display a window, but it doesn't sync/communicate with the Ledger Nano S after starting Ripple on the Ledger Nano S device.

I've turned off anti-virus, uninstalled/reinstalled, rebooted, etc., but nothing.  It doesn't work and there doesn't appear to be anything online to help people address the problem.

Hoping you can provide assistance.  Thank you for your time.

Scott

**Comment by amougel** [comment]
Hi,

The x64 version of the ledger wallet ripple has indeed some compatibility issues but there is no report of issue about the x86 yet. We will though investigate on try to reproduce on more windows platforms.

If you see the window of the app displaying, this means the launch was successfull and now you have another of the following issues: 
- You have the Ledger Manager, Bitcoin wallet, Ethereum Wallet or Electrum running in the background
- The ripple app on your device has the setting "Browser support" turned on (which should be turned off in order for the app to be able to work)
- Try another USB port and cable

If you have issue with the synchronization (incorrect balance, missing transactions and so), make sure you clicked on the "two arrows" on the top right corner of the app after launch. However, because of the recent events, the Ripple node wss://s2.ripple.com (which we do not control but use by default) has difficulties responding and thus, prevent our wallet from synchronizing. You can change the node you want to use, by unplugging your device and clicking on "change node" at the bottom of the opening screen.

**Comment by sdweber** [comment]
Greetings,

Thanks for getting back with me.

I’ve tried all three of your suggestions below…prior to sending in the trouble report…but no luck.  I’ve even tried running the app and device on two other machines…all Windows 10, as that is all I have…but with no luck.

At this point, I have my XRP sitting on an exchange and can’t get it to a safe wallet.  May have to set up and use an online digital wallet as a temporary solution (to move XRP off the exchange)…until I can use my two Ledger Nano S devices.

Please let me know what other options I have.  Can you do a remote login and help?  Would appreciate any help you can provide…I’m feeling a bit exposed and at a dead end.

Scott Weber
928-853-5006
