### ISSUE TITLE
Ledger ripple wallet 1.0.3 shows 0 XRP balance most of the time 

### ISSUE THREAD

**Issue by dredozubov** [LedgerHQ/ledger-wallet-ripple#31]
Wallet shows 0 XPR balance most of the time and refuses to send transactions because of insufficient funds. Sometimes it comes into its senses, but it's hard to say what triggers that. I tried plugging the ledger nano s at different time, reinstalled wallet more than 10 times. The log file exported by application is empty.

**Comment by yannickl** [comment]
I have the same issue here. I've tried to remove the app and reinstall, to cleanup the transaction history and the balance is still 0.

**Comment by mathieucivel** [comment]
Same for me, on Mac OS.

**Comment by vron503** [comment]
And me, ballance gone to 0, and I don't know what to do?  Google Chrome

**Comment by amougel** [comment]
The fact that the balance shows 0 or that you can't send transaction is something that is not due to the app itself and is not something that we can control yet. The app uses by default the official node wss///s2.ripple.com.

Under heavy load (which seems to be constantly the case since a month), this node tends to either:
- not respond
- disconnect unexpectedly
- provide incorrect/out of date balance

The only thing you can do is try to resync your app later in the day or host/used another node (you can change it by starting the app without your device plugged in and click on "change node")

We are currently deploying our own ripple node the allow our user to use the ripple network under heavy load but the feature is not out yet.

**Comment by Seadreamer** [comment]
This worked for me guys. Changed node to: wss://s1.ripple.com.  S2 does not work for me ever.
Thanks for all your input.
