### ISSUE TITLE
Sending error message

### ISSUE THREAD

**Issue by amirelayyan** [LedgerHQ/ledger-wallet-ripple#33]
Can't seem to be able to send XRP out of my wallet. Just stuck on:

Please wait
The transaction is being broadcasted to the network
and should be validated soon.

**Comment by amirelayyan** [comment]
Now I just get an unexpected error whenever I confirm that I would like to send my funds..

**Comment by cinvoke** [comment]
i cant confirm but sometimes i can and i get a network error too.

**Comment by amougel** [comment]
The fact that the balance shows 0 or that you can't send transaction is something that is not due to the app itself and is not something that we can control yet. The app uses by default the official node wss///s2.ripple.com.

Under heavy load (which seems to be constantly the case since a month), this node tends to either:
- not respond
- disconnect unexpectedly
- provide incorrect/out of date balance

The only thing you can do is try to resync your app later in the day or host/used another node (you can change it by starting the app without your device plugged in and click on "change node")

We are currently deploying our own ripple node the allow our user to use the ripple network under heavy load but the feature is not out yet.

**Comment by cinvoke** [comment]
my balance goes to zero and then back to normal too.
where are the other nodes listed?
any eta on your node deployment date or near date?
thanks..

**Comment by amougel** [comment]
I don't have info about list of nodes. The ETA should be about 1/2 weeks depending on how everything works out.

**Comment by amirelayyan** [comment]
Where can we find a list of nodes ?

**Comment by amirelayyan** [comment]
Ok so today I was able to transfer my funds
