### ISSUE TITLE
cant confirm transaction

### ISSUE THREAD

**Issue by Chrisco12** [LedgerHQ/ledger-wallet-ripple#34]
I cant confirm transaction because it doesn't prompt my ledger nano s.

**Comment by cinvoke** [comment]
this is happening on windows10 and mac el capitan

**Comment by amougel** [comment]
This might be due to the fact that you have no connection to the ripple network or that it closed unexpectedly. The new release will display a proper message soon.

Also:
The fact that the balance shows 0 or that you can't send transaction is something that is not due to the app itself and is not something that we can control yet. The app uses by default the official node wss///s2.ripple.com.

Under heavy load (which seems to be constantly the case since a month), this node tends to either:
- not respond
- disconnect unexpectedly
- provide incorrect/out of date balance

The only thing you can do is try to resync your app later in the day or host/used another node (you can change it by starting the app without your device plugged in and click on "change node")

We are currently deploying our own ripple node the allow our user to use the ripple network under heavy load but the feature is not out yet.
