### ISSUE TITLE
Ledger Ripple app not working on Windows 10

### ISSUE THREAD

**Issue by SaeedKhalifi** [LedgerHQ/ledger-wallet-ripple#49]
Hi All.

I recently bought a Ledger Nano S, installed Bitcoin and Ethereum chrome apps with no problem, updated the firmware to new 1.4.2 version. Everything is working fine.
I tried to install Ripple windows app,  the installation goes smoothly. But when I try to open the app, it gives me a generic windows errror stating 
"The application was unable to start correctly (0xc000007b). Click OK to close the application.
I'm running Windows 10 Version 1709 Build 16299.371 (latest fall creators update) and I can confirm OS is running fine. I'm an IT guy, I think OS is running ok.
I tried installer 1.0.3 x64 and x86 versions, i tried with Chrome closed, AV closed, but still no luck.
Here's a screenshot.
![ripple](https://user-images.githubusercontent.com/38560680/39051038-bde14206-44bc-11e8-99e6-83790066a0c4.jpg)
Any help would be much appreciated.
Thanks in advance

**Comment by amougel** [comment]
Since you re an IT guy, you could try to install [this version](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/tag/1.1.1) but you need to change the node to "wss://s2.ripple.com" and not use Ledger's Default node. (you can change the node by launching the app without plugging your device)

**Comment by SaeedKhalifi** [comment]
Installing 1.1.1 x64 fixed it for me, though I didn't change anything, be it node or anything else. Will I face issues later on or I'm good now?

**Comment by amougel** [comment]
You should change the node. Our own nodes will not provide a proper service
since there is no release using them yet so they are consider unused and
will be used for testing.

**Comment by SaeedKhalifi** [comment]
Can you please guide me on how to change the node?
I'm more of a Networking guy than a programmer.

**Comment by amougel** [comment]
Start the app without the device
Click on change node
Type wss://s2.ripple.com
Click OK
Then use the wallet as usual.

**Comment by SaeedKhalifi** [comment]
Thanks again.
I changed the node now.
But I bought Ripple and transfered it to my ledge prior. Will they be lost or changing nodes doesn't affect my ripple wallet address?

**Comment by amougel** [comment]
You sent your coins from the official blockchain. s2.ripple is connected to
the official blockchain, so your funds will be there

On Apr 20, 2018 15:36, "Joviall" <notifications@github.com> wrote:

Thanks again.
I changed the node now.
But I bought Ripple and transfered it to my ledge prior. Will they be lost
or changing nodes doesn't affect my ripple wallet address?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LedgerHQ/ledger-wallet-ripple/issues/49#issuecomment-383098087>,
or mute the thread

**Comment by SaeedKhalifi** [comment]
So transferring ripple to my ledger prior to changing the node, won't result in loss of my ripple, am I right?

**Comment by amougel** [comment]
You re right. Your address does not change between nodes.

**Comment by SaeedKhalifi** [comment]
Thanks again for helping me out and giving clear information, really appreciate it Amougel 😄
