### ISSUE TITLE
Cann't see my balance by wss://s2.ripple.com on Ledger

### ISSUE THREAD

**Issue by SaeedKhalifi** [LedgerHQ/ledger-wallet-ripple#50]
Hi there.
I was having issues installing Ledger ripple app and I installed version 1.1.1 and it fixed it for me.
I changed the node to wss://s2.ripple.com, but it couldn't retrieve my balance and transactions information.
So I looked it up and changed the address to wss://s1.ripple.com and it's showing my balance now.
What difference is there between s1 and s2?
Should I change it back to s2? if so, how can I get it to work with s2 since it has difficulty retrieving my information?
Even when set to s1.ripple.com, though successfully retrieving my information, the Retry button at the top right corner keeps spinning. Is that normal?
Thanks in advance

**Comment by amougel** [comment]
From their doc : 
Currently Ripple (the company) maintains a set of public WebSocket servers at:
s1.ripple.com | 443 | wss:// only ->  general purpose server
s2.ripple.com | 443 | wss:// only -> full-history server

The only difference between s2 and s1 is that s1 will not show you old transactions.
It happens often that s1 and/or s2 are not available because of the load of users.
