### ISSUE TITLE
Doesn’t recognise Ripple app being open on device

### ISSUE THREAD

**Issue by sudokonami** [LedgerHQ/ledger-wallet-ripple#6]
With the device connected via USB, unlocked, and the Ripple app open on the device, this application just sits there on the following screen:

![ledger-wallet-ripple](https://user-images.githubusercontent.com/30656533/28872396-e1cdee12-7780-11e7-8c92-2a3cab2e23e1.jpg)

Other wallet apps, such as those for BTC and ETH (note that these are Chrome apps, not native like this one) detect their respective applications being open as expected.

Device: Ledger Wallet Nano S
Client: Ledger Wallet Ripple, version 1.0.2 (downloaded from [this release](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/tag/1.0.2))
OS: Mac OS 10.12.6

**Comment by amougel** [comment]
Make sure you don't have the bitcoin or ethereum wallet or manager running in the back ground and try again. Also, please contact support for such inquiries.

**Comment by sudokonami** [comment]
> Make sure you don't have the bitcoin or ethereum wallet or manager running in the back ground and try again.

I can confirm that no other wallet apps, nor the manager app are running in the background, and I’m still seeing the same behaviour.

> Also, please contact support for such inquiries.

With all due respect, with this being an open source application I would have thought that it’s in the interests of both the Ledger team and your customer base to be transparent about open issues with your applications—rather than closing without resolution and punting people off to support.

**Comment by amougel** [comment]
This is not a matter of transparency. The code is still available for you to see and all known issues are disclosed on our [support page](http://support.ledgerwallet.com/help_center) as soon as they are uncovered.

We appreciate the clarity of your post but github as to stay clean for source management and open source contributions and does not aim to be used as a customer support platform. 

We invite you to submit a new ticket so that we can help you with solve your issue on an appropriate channel in a efficient manner.
